### ISSUE TITLE
Asciidoc files are only rendered once when using LiveReload

### ISSUE THREAD

**Issue by lask79** [asciidoctor/asciidoctor-firefox-addon#26] opened 2015-04-06 18:36 UTC
Hi,

I am having problems using the Asciidoctor Firefox addon in combination with LiveReload and the JBoss Tools LiveReload (http://tools.jboss.org/features/livereload.html).

When I 
* start the LiveReload server, send an *.adoc file to the browser, 
* create a connection in firefox with the LiveReload Addon, 
* activate the Asciidoctor Firefox Addon and
* change the *.adoc file
then only the first change is triggering the new rendering of the *.adoc files in Firefox. The second change will not be displayed. 

When I disable the Asciidoctor Addon then every change is triggering an update of the raw text so the LiveReload connection itself seems to work.

Any idea?

**Comment by Mogztter** [comment] 2015-04-06 21:47
Hi @lask79 and thanks for using the Firefox add-on.
This is a known issue and we already solved it on the Chrome extension (meaning the fix will be easy yay!).
If I remember correctly the issue was that the LiveReload is injecting a script in the HTML page but the extension replaces the whole content with the converted html.
We fix this issue by saving existing script in the page. If you are interested in live reload, the chrome extension have a built-in feature (no need to install LiveReload).

I will try to backport this fix and publish a new version to the Firefox add-on website.

**Comment by lask79** [comment] 2015-04-09 13:46
That would be great if you could fix this soon. Chrome is not allowed at our customer site and therefor not an option for us.

Regards
Lasse

**Comment by Mogztter** [comment] 2015-05-08 13:30
@lask79 I pushed to master a new version to save scripts before updating the document body (and then restore them). Could you test if this fix the issue ?

**Comment by maxandersen** [comment] 2015-05-27 09:55
How do I test this ? is it already live ? if yes, it seem to have been fixed. And yes I did see the same issue described here in the past thinking it was our livereload implementation that somehow was broken; good to see it is just limited to asciidoctor.js firefox add on. ;)

**Comment by Mogztter** [comment] 2015-05-27 17:52
> How do I test this ? is it already live ?

I don't think so :smile: 
How did you install the add-on ? from the asciidoctor.org website or from https://addons.mozilla.org ? And can you tell me the version you are running ?

**Comment by lask79** [comment] 2015-05-28 09:05
How can I test this when this is not released yet?

**Comment by Mogztter** [comment] 2015-05-29 19:26
Actually 0.3.0 sounds good, are you still having the issue with 0.3.0 ?

If you are using Firefox 38+, you can build an xpi file with `jpm`: https://github.com/asciidoctor/asciidoctor-firefox-addon#local-build

Then you can simply drag and drop it on Firefox to install the Add-on.

If you are using Firefox < 38 you need to use the Firefox Add-on SDK: https://github.com/asciidoctor/asciidoctor-firefox-addon/blob/3020eaba83450b817c5ff6251ae3daffff1ea547/README.adoc#local-build

You also need to checkout efaa65c5f6151867a9a06cf987d5e2dd51f2a8eb (because master is currently targeting Firefox 38+ and is only compatible with `jpm`)

If this sounds too complicated I can produce a preview version and attach it on GitHub ?

**Comment by maxandersen** [comment] 2015-06-12 11:42
I built this and it unfortunately does not seem to fix the bug

chrome works.

**Comment by Mogztter** [comment] 2015-06-15 21:38
@maxandersen Could you give me a description of your environment so I can try to reproduce this issue ?

**Comment by maxandersen** [comment] 2015-06-16 07:51
Running latest firefox w/asciidoctor plugin and livereload plugin using JBoss Tools Livereload feature (import project, right click .adoc file  and use Show In > Browse w/livereload) - I do not think this is specific to jboss tools livereload though.

Then in firefox enable livereload and then edit to save file. See the reload happen.
edit and save file again - no reload happens.

enable livereload - things work again, but just once.

For "pure" html livereload works just fine. Only affects asciidoc.

For me this implies that the livereload feature does work, but somehow asciidoctor.js "resets" the reload feature which is unfortunate.

**Comment by Mogztter** [comment] 2015-06-27 10:10
@maxandersen thanks for the detailed procedure, I'm downloading JBoss Developer Studio 8.1.0.GA to reproduce, I will let you know

**Comment by maxandersen** [comment] 2015-06-29 13:16
note, it also fails without jboss developer studio.

**Comment by Mogztter** [comment] 2015-06-29 16:01
Should be OK with my last commit 53bc70dcb8cba83eeec4c0a0f97ea67793d22032

**Comment by lask79** [comment] 2015-07-01 10:28
Now it works like a charm. Thanks for fixing.

**Comment by Mogztter** [comment] 2015-07-02 17:17
Cool, I will published a new version to the AMO :smile:

**Comment by mojavelinux** [comment] 2015-07-02 22:15
:+1: Nice work!

**Comment by Mogztter** [comment] 2015-07-04 17:28
Resolved by 53bc70d

**Closed by Mogztter** 2015-07-04 17:28 UTC

**Comment by maxandersen** [comment] 2015-07-09 11:12
any ETA on this ? https://addons.mozilla.org/en-US/firefox/addon/asciidoctorjs-live-preview/ still says 0.3.2 ?

**Comment by Mogztter** [comment] 2015-07-09 11:36
I'm waiting review on #33 and #34 before publishing the new version

**Comment by Mogztter** [comment] 2015-07-16 16:27
@maxandersen I submitted v0.4.0 to AMO

**Comment by maxandersen** [comment] 2015-07-17 12:35
cool, do you know how long it takes from submit to it showing up  for now old 3.x is still there.

**Comment by Mogztter** [comment] 2015-07-17 12:37
Last time was 2 weeks or so, I will let you know when I heard from them.

**Comment by maxandersen** [comment] 2015-07-21 08:16
just to verify that 0.4.0 built from source works like a charm! thanks.

**Comment by mojavelinux** [comment] 2015-07-21 08:50
:+1:

**Comment by Mogztter** [comment] 2015-10-24 11:29
@maxandersen I have a good news!
> Your add-on, Asciidoctor.js Live Preview 0.4.0, has been fully reviewed by an editor and is now available for download in our gallery at https://addons.mozilla.org/addon/asciidoctorjs-live-preview/

3 months to review a minor update... well done!

**Comment by maxandersen** [comment] 2015-10-26 11:52
awesome!

**Comment by mojavelinux** [comment] 2015-10-26 21:32
:beers:
