### ISSUE TITLE
Fix extension for Firefox 57 quantum update

### ISSUE THREAD

**Issue by r0ckarong** [asciidoctor/asciidoctor-firefox-addon#66] opened 2017-10-06 13:18 UTC
The next version will be coming out in November and many people are currently using the betas. Can you prepare the extension to work with FF 57? Not sure how much of a refactor this will be because of the new rendering engines etc.

**Comment by Mogztter** [comment] 2017-10-06 15:20
Hello @r0ckarong, thanks for pointing this out.
The plan is to use the new WebExtension API. Since this API is basically the Chrome Extension API, the Chrome extension will replaced the Firefox extension: https://github.com/asciidoctor/asciidoctor-chrome-extension

Some ground work have already been done: https://github.com/asciidoctor/asciidoctor-chrome-extension/pull/151

I'm waiting on the Asciidoctor.js 1.5.6 release to fix the last issues, then I will do a release of the "Chrome" extension that will be compatible witch Chrome, Firefox and Opera.
Having said that, the "Chrome" extension should already be compatible with Firefox 57. If you want to give it a try, you can clone the `asciidoctor-chrome-extension` repository, and load the `app` directory (or create a zip from the `app` directory)

**Comment by r0ckarong** [comment] 2017-10-09 10:54
What you mean is to add a temporary extension right? I tried installing a Zip of the app folder contents as an Add-on and it failed. 

What I did to make it work was to go to `about:debugging` and then load the "manifest.json" from the app folder with the "Load temporary add-on" button. Now it seems to work fine.

Looking forward to seeing this work out of the box.

**Comment by Mogztter** [comment] 2017-10-09 12:51
> What I did to make it work was to go to about:debugging and then load the "manifest.json" from the app folder with the "Load temporary add-on" button. Now it seems to work fine.

Yes, that's exactly what I meant, sorry if my reply wasn't clear enough :neutral_face: 

> Looking forward to seeing this work out of the box.

Did you install the extension from the Firefox Addon Website https://addons.mozilla.org/en/firefox/addon/asciidoctorjs-live-preview/ ?
Please note that the review process on AMO (addons.mozilla.org) is really long and tedious so we've decided to distribute the extension through GitHub and not https://addons.mozilla.org anymore.

I will also submit the new version on AMO though but the review process can take months, so keep an eye on GitHub :wink:

**Comment by mojavelinux** [comment] 2017-10-10 06:42
> I will also submit the new version on AMO though but the review process can take months, so keep an eye on GitHub :wink:

I think this is the right strategy. We distribute on GitHub so that users who don't want to wait don't have to (which probably includes all the early adopters and testers). We distribute on AMO for those that can only install this way, but they'll have to be patient because of Mozilla's policy.

**Comment by Mogztter** [comment] 2017-10-29 09:43
@r0ckarong Could you try to install the latest version: https://addons.mozilla.org/en-us/firefox/addon/asciidoctorjs-live-preview ?

**Comment by tracphil** [comment] 2017-10-29 12:15
That worked for me on Fedora using FF 57. Thank you @r0ckarong !!

**Comment by Mogztter** [comment] 2017-10-29 14:07
Awesome :+1: 
I'm waiting to hear from @r0ckarong before closing this issue.

**Comment by ggrossetie** [comment] 2017-11-20 17:03
Other users had confirmed that the extension is working fine.
Closing...

**Closed by ggrossetie** 2017-11-20 17:03 UTC
