### ISSUE TITLE
Eagerly transform all text/plain responses

### ISSUE THREAD

**Issue by mareknovotny** [asciidoctor/asciidoctor-firefox-addon#64] opened 2017-04-24 08:15 UTC
Hi, 
I noticed that enabled Asciidoc preview eagerly transform all my text/plain pages/responses in browser. Even I tried to use `view-source:///` and it is re-rendered with it. 

I cannot find any option to disable it for certain remote URL/type of content. I thought it should be enabled only for local preview of files.

**Comment by Mogztter** [comment] 2017-04-24 08:56
Hi @mareknovotny, I think it is a duplicate of https://github.com/asciidoctor/asciidoctor-firefox-addon/issues/61#issuecomment-287631535

Could you please update to version [0.5.5](https://github.com/asciidoctor/asciidoctor-firefox-addon/releases/tag/v0.5.5) ?

**Comment by mareknovotny** [comment] 2017-04-24 09:52
@Mogztter great, that helped.

Btw, update from Firefox Addons doesn't work, I needed to install it manually from downloaded xpi file. Is that known issue too?

**Closed** 2017-04-24 09:52 UTC

**Comment by Mogztter** [comment] 2017-04-24 13:34
@mareknovotny you're welcome :wink: 

> Btw, update from Firefox Addons doesn't work, I needed to install it manually from downloaded xpi file. Is that known issue too?

The review process on https://addons.mozilla.org/fr/firefox/ is really long so we've decided to host a self signed version of the extension on GitHub.
