### ISSUE TITLE
Every text file is rendered

### ISSUE THREAD

**Issue by ojeulin** [asciidoctor/asciidoctor-firefox-addon#61] opened 2017-02-14 16:25 UTC
Problem: When I open a local asciidoc file, renamed "foo.txt" or "foo", it is rendered in HTML.
Firefox: 51.0.1 (64 bits)
OS: GNU/linux
I tested with a file located in 2 directories:
- file:///home/ojeulin/tmp/foo  (and …/foo.txt)
- file:///home/ojeulin/Documents/conferences/foo  (and …/foo.txt)

**Comment by Mogztter** [comment] 2017-02-14 17:00
This is weird, we are using the following RegExp: https://github.com/asciidoctor/asciidoctor-firefox-addon/blob/fb2598e0b734d182064cd9cb16a739efbbc1071f/data/asciidocify.js#L5

```javascript
var regexpAdFile = /\.a(sciidoc|doc|d|sc)$|\.a(sciidoc|doc|d|sc)\?|/i;
```

Could you please attach a screenshot ?

**Comment by ojeulin** [comment] 2017-02-16 14:36
Here are 2 screenshots, with the extension on and off.

![text file - with extension off](https://cloud.githubusercontent.com/assets/10844327/23025034/c31448ce-f45c-11e6-814d-f74af20e802f.png)
![text file - with extension on](https://cloud.githubusercontent.com/assets/10844327/23025035/c31735de-f45c-11e6-95ed-a0f07b0bc184.png)
![vim file - with extension off](https://cloud.githubusercontent.com/assets/10844327/23025036/c3194d56-f45c-11e6-8754-5569d6c914e7.png)
![vim file - with extension on](https://cloud.githubusercontent.com/assets/10844327/23025037/c31beb4c-f45c-11e6-99b8-5599fbe991f6.png)

**Comment by Mogztter** [comment] 2017-02-16 18:10
Thanks!
I can reproduce this issue. What version of the extension are you using ?

**Comment by ojeulin** [comment] 2017-02-17 15:59
Ah, sorry, version 0.5.1

**Comment by d-nnis** [comment] 2017-03-18 17:31
I can confirm this. It happens on my setup as well: version 0.5.3
In conjunction with [Markdown Viewer](https://github.com/Thiht/markdown-viewer) I get to see a markdown file (file is named `README.md` really) rendered with Asciidoc

**Comment by Mogztter** [comment] 2017-03-18 17:46
It should be fixed in https://github.com/asciidoctor/asciidoctor-firefox-addon/pull/62
Could someone build the extension from this branch to confirm that the issue is gone ?

**Comment by d-nnis** [comment] 2017-03-19 15:17
Can confirm once again, on a different computer.
Firefox 45.8.0, Asciidoctorjs-live-preview), this time version 0.5.1 from the official Mozilla [Addon-Site](https://addons.mozilla.org/en-US/firefox/addon/asciidoctorjs-live-preview/).
[This site](https://deb.nodesource.com/setup_dev) gets rendered.
This is really an undiserable situation.
Is this something about my setups?
Can I show more details so that you can fix this tiring issue?

**Comment by d-nnis** [comment] 2017-03-19 15:17
As a quick fix: Offer to setup a keyboard shortcut to activate/de-activate the addon quickly :-D

**Comment by mojavelinux** [comment] 2017-03-19 16:02
I don't think there's any confusion that the published version has the
wrong behavior. Any fix, whether the correct fix or a workaround, requires
publishing a new version. And the correct fix has already been determined.
So it's just a matter of getting the new version published at this point.

**Closed** 2017-03-19 16:55 UTC
Labels: bug

**Comment by Mogztter** [comment] 2017-03-19 17:15
Version 0.5.5 released.
Could you please uninstall the extension and install version 0.5.5: https://github.com/asciidoctor/asciidoctor-firefox-addon/releases/tag/v0.5.5

1. Download asciidoctor-firefox-addon-0.5.5-signed.xpi
2. Drag and drop the file into Firefox
3. Install, restart the browser
4. Enjoy! (only `.ad`, `.adoc`, `.asc`, `.asciidoc` should be rendered)

**Comment by d-nnis** [comment] 2017-03-19 18:42
Yes! I do enjoy (only asciidoc-files) with version 0.5.5.

Thanks for working it out.
 :honeybee:

**Comment by Mogztter** [comment] 2017-03-19 20:10
Awesome :beetle: :smile:

**Comment by d-nnis** [comment] 2017-03-19 20:51
My life now seems so much better with emojis. :rage2: (It's like I'm turning teenage again.) What would I do without them? :shell:

It is a pity though, github does not support emoji-sounds. I would definitely go for `/play trololo`
( Check [here](https://www.webpagefx.com/tools/emoji-cheat-sheet/), scroll to the bottom if your're interested ;-) )

**Comment by ojeulin** [comment] 2017-03-20 08:29
Yes, it works, thanks 👍
