### ISSUE TITLE
A-icon doesn't show: unable to see preview

### ISSUE THREAD

**Issue by Charles89** [asciidoctor/asciidoctor-firefox-addon#59] opened 2016-11-04 16:58 UTC
I just installed the asciidoctor preview extension in Firefox from here: https://addons.mozilla.org/en-US/firefox/addon/asciidoctorjs-live-preview/ but unfortunately the local asc-file I have is displayed in plain text. There's also no A-button/icon to switch to the preview. I restarted Firefox and it says the addon is installed.

asciidoctorjslivepreview 0.5.1
Firefox 49.0.2

**Comment by Mogztter** [comment] 2016-11-04 18:21
Hello @Charles89 
If you go to `about:addons`, is the addon installed and enabled ? Did you try to "Customize..." the toolbar ?

![customize](https://cloud.githubusercontent.com/assets/333276/20017437/e329677e-a2c3-11e6-9896-d4844ca1e4d0.PNG)

**Comment by Charles89** [comment] 2016-11-05 09:25
When I goto about:addons I see the addon installed and enabled. When I goto Customize the toolbar it is not listed.

![2016-11-05 10_23_18-add-ons manager](https://cloud.githubusercontent.com/assets/14233465/20029054/26c9bf28-a342-11e6-94a8-fac519889cbc.png)

![2016-11-05 10_23_46-mozilla firefox](https://cloud.githubusercontent.com/assets/14233465/20029056/2c5d1638-a342-11e6-84cb-102a7cf2d1fa.png)

**Comment by Mogztter** [comment] 2016-11-05 20:00
Indeed this is weird.
Maybe an icon size is missing, what is the resolution of your screen ? Do you have any error if you debug the extension ?

**Comment by Charles89** [comment] 2016-11-05 20:24
My resolution is 1920 x 1080 and font size is at 100%. Can you give me directions on how to debug the extension? I enabled logging of extensions and fired up the browser console but couldn't find anything that looked like it was created by asciidoc. I did see this however:

![2016-11-05 21_17_13-browser console](https://cloud.githubusercontent.com/assets/14233465/20033323/1fc1bf58-a39e-11e6-8eaf-9191058d3c15.png)

**Comment by Charles89** [comment] 2016-11-24 10:43
This icon seems to prevent me from using it. Can anyone update the icon with a different copy?

**Comment by Mogztter** [comment] 2016-12-03 17:16
Hello @Charles89 

Sorry about the late reply but I can't reproduce this issue. So I don't really know what is happening...
`icon.png` is not blank in the xpi file.
Could you try to reinstall the Add-on from GitHub: https://github.com/asciidoctor/asciidoctor-firefox-addon/releases/tag/v0.5.4

1. Download the xpi file
2. Drag'n'drop the xpi file on Firefox
3. Accept and install

Thanks

**Comment by Charles89** [comment] 2016-12-05 08:16
Thank you for the suggestion: I uninstalled and reinstalled from the link you gave me. Unfortunately it didn't work: I still don't see an icon when I customize Firefox. However, I do see that icon.png shows a picture when I extract the file from the xpi. Looks like I have to accept this isn't going to work. If you have any new ideas on what might be causing this, or if you want me to run some debug-version: please let me know.

**Comment by Mogztter** [comment] 2016-12-05 10:07
Ok next step is to create a debug-version with different sizes of the icon

**Comment by Charles89** [comment] 2016-12-05 10:33
This is weird: I was setting up a development environment using [this info](https://developer.mozilla.org/en-US/Add-ons/Setting_up_extension_development_environment) and when I use that debug-profile, the icon **is** showing.

**Comment by Mogztter** [comment] 2016-12-05 15:31
Interesting...
If you found the setting that cause the issue, please share this information. That way, if another user hits the same issue he can fix it by himself :+1: 

Can I close this issue ?

**Comment by Charles89** [comment] 2016-12-05 15:37
The file contains about 135 settings, so I'm not too keen on finding out which particular settings was causing this behavior. My advise is to delete the prefs.js whenever you encounter this situation ;-)
Please feel free to close to issue.

**Comment by Mogztter** [comment] 2016-12-05 15:45
> The file contains about 135 settings, so I'm not too keen on finding out which particular settings was causing this behavior. 

No worries :wink: 

> My advise is to delete the prefs.js whenever you encounter this situation ;-)
Please feel free to close to issue.

Ok thanks for your time on tracking this issue.

**Closed by Mogztter** 2016-12-05 15:45 UTC
Labels: question, wontfix
